server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog
    username: root
    password: liuyong1993
    initialSize: 5
    MaxActive: 5
  redis:
    port: 6379
    host: localhost
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: 1000
        max-idle: 10

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

code:
  success: 200
  error: -1

#file:
#  uploadFolder: /