server:
  port: 8081
#spring:
#  profiles:
#    active: dev
#---
#server:
#  port: 8083
#spring:
#  profiles: dev
#---
#
#server:
#  port: 8083
#spring:
#  profiles: prod


#person:
#  name: zhangsan
#  age: 18
#  lists:
#    - list
#    - zhaoliu
