server:
  port: 8081
#spring:
#  profiles:
#    active: dev
#---
#server:
#  port: 8083
#spring:
#  profiles: dev
#---
#
#server:
#  port: 8083
#spring:
#  profiles: prod


#person:
#  name: zhangsan
#  age: 18
#  lists:
#    - list
#    - zhaoliu
spring:
  datasource:
    username: root
    password: liuyong1993
    url: jdbc:mysql://127.0.0.1:3306/blog
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    MaxActive: 5
